###############################################
#Developed by: Tal M & Baruch G
#Purpose: Ansible
#Date:20/05/2025
#Version: 0.0.1
###############################################
---

- name: Service Setup
  hosts: all
  become: true
  tasks:
    - name: create user
      user:
        name: "app_user"
        shell: /bin/bash
        create_home: yes
    - name: copy app files
      copy:
        content: |
          #!/bin/bash
          echo "Hello, world!"
        dest: /tmp/hello.sh
        mode: '0755'


    - name: Run Hello World script
      shell: /tmp/hello.sh
      register: hello_result


    - name: Show script output
      debug:
        var: hello_result.stdout